# -*- coding: utf-8 -*-
"""AutoGluon v1.5.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ynNAJjnBJwd8NBpoLe2KjAzeVyN21DsA

<img src="https://auto.gluon.ai/stable/_static/autogluon.png" width="300" alt="AutoGluon"/>

# AutoGluon

AutoGluon은 AWS에서 개발한 오픈소스 AutoML 라이브러리입니다. 몇 줄의 코드만으로 표 형태 데이터, 이미지, 텍스트, 시계열 데이터에 대해 정확도가 높은 머신러닝 및 딥러닝 모델을 학습하고 배포할 수 있습니다.

## 학습 목표

- AutoGluon의 세 가지 주요 모듈 이해: `Tabular`, `Multimodal`, `TimeSeries`
- 각 모듈의 `Predictor`를 사용한 학습, 예측, 평가 방법
- AutoGluon이 내부적으로 수행하는 모델 ensemble 및 stacking의 개념

## 본 실습 환경

- Python 3.10 이상 필요 (AutoGluon 1.5 기준)
- **GPU 사용 권장**: `런타임` > `런타임 유형 변경` > `T4 GPU` 선택

## Installation

AutoGluon 1.5부터는 `uv`를 이용한 설치가 공식적으로 권장됩니다. `uv`는 기존 pip보다 의존성 해결과 설치 속도가 빠릅니다.
"""

!pip install -U uv -q
!uv pip install autogluon --system -q

"""# 1. Tabular

표 형태(tabular) 데이터로 특정 열의 값을 예측하는 가장 일반적인 작업입니다. AutoGluon의 `TabularPredictor`는 LightGBM, XGBoost, CatBoost, Random Forest, Neural Network 등 여러 모델을 자동으로 학습하고 ensemble하여 예측합니다.

두 개의 핵심 클래스를 사용합니다.

- `TabularDataset`: 데이터 로드 (`pandas.DataFrame`의 하위 클래스)
- `TabularPredictor`: 모델 학습 및 예측
"""

from autogluon.tabular import TabularDataset, TabularPredictor

"""## 1.1 Example Data

본 실습에서는 [Nature 7887](https://www.nature.com/nature/volumes/600/issues/7887)의 커버 스토리 논문 [Advancing mathematics by guiding human intuition with AI](https://www.nature.com/articles/s41586-021-04086-x.pdf)의 dataset을 사용합니다.

Knot의 속성을 기반으로 knot signature를 예측하는 것이 목표입니다. [원본 데이터](https://github.com/deepmind/mathematics_conjectures/blob/main/knot_theory.ipynb)에서 10,000개의 훈련 예제와 5,000개의 테스트 예제를 샘플링했습니다.

`TabularDataset`은 `pandas.DataFrame`의 하위 클래스이므로 `DataFrame`의 모든 메서드를 그대로 사용할 수 있습니다.
"""

data_url = 'https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/'
train_data = TabularDataset(f'{data_url}train.csv')
train_data.head()

"""타겟은 18개의 정수 값을 갖는 `signature` 열입니다. pandas는 이 열을 numerical로 인식하지만, AutoGluon이 학습 과정에서 이를 categorical (multi-class classification)로 자동 인식합니다."""

label = 'signature'
train_data[label].describe()

"""## 1.2 Training

`TabularPredictor`에 label 열 이름을 지정한 후 `fit()`을 호출하면 학습이 시작됩니다.

별도의 parameter 지정 없이도 AutoGluon은 다음을 자동으로 수행합니다.

1. 문제 유형 추론 (binary classification, multi-class classification, regression)
2. Feature engineering (numerical, categorical, text, datetime 열 자동 처리)
3. 여러 모델 학습 (LightGBM, XGBoost, CatBoost, Random Forest, Neural Network 등)
4. 모델 ensemble을 통한 최종 predictor 생성

실습 시간을 고려하여 `time_limit=120`(2분)을 지정합니다. 일반적으로 시간 제한이 길수록 더 다양한 모델을 학습하여 성능이 향상됩니다.
"""

predictor = TabularPredictor(label=label).fit(
    train_data,
    time_limit=120,  # 2분 (실습용)
)

"""### 학습 옵션 (참고)

`fit()`에는 학습 강도를 조절하는 `presets` parameter가 있습니다.

| Preset | 특징 |
|--------|------|
| `medium_quality` (default) | 빠른 학습, 적당한 성능 |
| `good_quality` | medium보다 더 많은 모델 |
| `high_quality` | 더 큰 ensemble, 더 긴 학습 시간 |
| `best_quality` | 최대 성능 (production용) |
| `extreme` (1.4+) | 3만 샘플 이하 데이터셋에서 SOTA |

사용 예: `predictor = TabularPredictor(label=label).fit(train_data, presets='best_quality', time_limit=3600)`

## 1.3 Prediction

학습된 predictor로 별도의 데이터셋에 대해 예측을 수행할 수 있습니다.
"""

test_data = TabularDataset(f'{data_url}test.csv')

y_pred = predictor.predict(test_data.drop(columns=[label]))
y_pred.head()

"""## 1.4 Evaluation

`evaluate()` 함수는 모델 학습에 사용되지 않은 데이터셋에서 predictor 성능을 측정합니다.
"""

predictor.evaluate(test_data, silent=True)

"""### Leaderboard

`leaderboard()` 함수는 AutoGluon이 학습한 각 개별 모델의 성능을 테이블로 보여줍니다. 어떤 모델이 가장 잘 작동하는지, 학습 및 예측 시간이 얼마나 걸리는지 확인할 수 있습니다.
"""

predictor.leaderboard(test_data)

"""# 2. Multimodal

`MultiModalPredictor`는 이미지, 텍스트, 표 형태 데이터를 함께 입력으로 받을 수 있는 deep learning 모델 zoo입니다. 여러 modality를 자동으로 인식하고 적절한 모델을 선택하여 학습합니다.

내부적으로:

1. 문제 유형(Classification 또는 Regression) 자동 추론
2. Feature modality 감지 (이미지, 텍스트, 표 등)
3. Modality별로 적절한 모델 선택 (CNN, Transformer 등)
4. 여러 backbone이 사용되는 경우 late-fusion model (MLP 또는 Transformer) 추가
"""

import os
import warnings
import numpy as np

warnings.filterwarnings('ignore')
np.random.seed(123)

"""## 2.1 Example Data

[PetFinder dataset](https://www.kaggle.com/c/petfinder-adoption-prediction)의 단순화된 버전을 사용합니다. 입양 프로필을 기반으로 반려동물 입양률을 예측하는 것이 목표입니다.

원본은 5개 클래스의 multi-class classification이지만,
본 실습에서는 binary classification으로 단순화했습니다 (입양 속도를 두 가지 범주로 분류합니다: 0(느림)과 1(빠름).)

먼저 PetFinder dataset이 포함된 zip 파일을 다운로드하여 현재 작업 디렉토리에 압축을 풉니다.
"""

from autogluon.core.utils.loaders import load_zip

download_dir = './ag_multimodal_tutorial'
zip_file = 'https://automl-mm-bench.s3.amazonaws.com/petfinder_for_tutorial.zip'

load_zip.unzip(zip_file, unzip_dir=download_dir)

"""다음으로, pandas를 사용하여 dataset의 CSV 파일을 `DataFrame`을 읽고,  'AdoptionSpeed' column을 지정합니다."""

import pandas as pd

dataset_path = f'{download_dir}/petfinder_for_tutorial'

train_data = pd.read_csv(f'{dataset_path}/train.csv', index_col=0)
test_data = pd.read_csv(f'{dataset_path}/test.csv', index_col=0)

label_col = 'AdoptionSpeed'

train_data['Images'][0]

"""PetFinder dataset의 이미지 열은 세미콜론(`;`)으로 구분된 여러 이미지 경로를 포함합니다. image directory와 함께 제공되며, 데이터의 일부 레코드에는 여러 이미지가 연관되어 있습니다.

AutoGluon의 multimodal dataframe 형식에서는 이미지 열에 단일 이미지 파일의 path string이 포함되어야 합니다.

이 예제에서는 image feature 열을 첫 번째 이미지로만 제한하고 현재 디렉토리 구조에 맞게 모든 것을 올바르게 설정하기 위해 몇 가지 path manipulation을 수행합니다.
"""

image_col = 'Images'

# 세미콜론으로 구분된 여러 이미지 중 첫 번째만 사용
train_data[image_col] = train_data[image_col].apply(lambda ele: ele.split(';')[0])
test_data[image_col] = test_data[image_col].apply(lambda ele: ele.split(';')[0])

def path_expander(path, base_folder):
    path_l = path.split(';')
    return ';'.join([os.path.abspath(os.path.join(base_folder, path)) for path in path_l])

# 상대 경로를 절대 경로로 변환
train_data[image_col] = train_data[image_col].apply(lambda ele: path_expander(ele, base_folder=dataset_path))
test_data[image_col] = test_data[image_col].apply(lambda ele: path_expander(ele, base_folder=dataset_path))

train_data['Images'][0]

"""각 동물의 입양 프로필에는 사진, 텍스트 설명, 나이, 품종, 이름, 색상 등 다양한 표 형태 정보가 포함되어 있습니다. 한 예제의 이미지와 설명 텍스트를 살펴봅니다."""

from IPython.display import Image, display

example_row = train_data.iloc[0]
example_image = example_row[image_col]

pil_img = Image(filename=example_image)
display(pil_img)

example_row['Description']

"""## 2.2 Training

데이터가 적절한 형식이 되었으므로 `MultiModalPredictor`로 학습합니다. 짧은 데모를 위해 학습 시간을 2분으로 제한합니다.
"""

from autogluon.multimodal import MultiModalPredictor

predictor = MultiModalPredictor(label=label_col).fit(
    train_data=train_data,
    time_limit=120
)

"""## 2.3 Prediction

학습된 모델로 test dataset의 레이블을 예측합니다.
"""

predictions = predictor.predict(test_data.drop(columns=label_col))
predictions[:5]

"""Classification 문제의 경우 각 클래스에 대한 예측 확률도 얻을 수 있습니다."""

probs = predictor.predict_proba(test_data.drop(columns=label_col))
probs[:5]

"""## 2.4 Evaluation

Test dataset에 대해 [ROC AUC](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html) 등 원하는 metric으로 평가할 수 있습니다.
"""

scores = predictor.evaluate(test_data, metrics=["roc_auc"])
scores

"""# 3. Time Series

`TimeSeriesPredictor`는 단변량 시계열 데이터에 대해 확률적(probabilistic) 예측을 생성합니다. 단순한 통계 모델부터 최신 deep learning 모델까지 다양한 알고리즘을 자동으로 학습하고 ensemble합니다.

- **Simple forecasting**: ARIMA, ETS, Theta
- **Deep learning**: DeepAR, Temporal Fusion Transformer
- **Tree-based**: LightGBM 기반 RecursiveTabular, DirectTabular
- **Foundation model**: Chronos-2 (AutoGluon 1.5에 추가)
- **Ensemble**: 위 모델들의 가중 결합

본 실습에서는 [M4 forecasting competition](https://www.sciencedirect.com/science/article/pii/S0169207019301128) 데이터셋의 일부로 시간별 예측을 수행합니다.

## 3.1 Loading time series data

`autogluon.timeseries`는 두 개의 핵심 클래스를 제공합니다.

- `TimeSeriesDataFrame`: 여러 시계열을 저장하는 데이터 구조
- `TimeSeriesPredictor`: 모델 학습, 튜닝, 선택, 예측 수행
"""

import pandas as pd
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor

df = pd.read_csv("https://autogluon.s3.amazonaws.com/datasets/timeseries/m4_hourly_subset/train.csv")
df.head()

"""AutoGluon은 [long format](https://doc.dataiku.com/dss/latest/time-series/data-formatting.html#long-format) 시계열 데이터를 입력으로 받습니다. 각 행은 단일 시점의 관측치를 표현하며, 최소 3개 열이 필요합니다.

- 시계열 고유 ID (`item_id`)
- 타임스탬프 (`timestamp`)
- 타겟 값 (`target`)

열 이름은 자유롭게 지정 가능하지만, `TimeSeriesDataFrame` 생성 시 명시해야 합니다.
"""

train_data = TimeSeriesDataFrame.from_data_frame(
    df,
    id_column="item_id",
    timestamp_column="timestamp"
)
train_data.head()

"""`TimeSeriesDataFrame`에 저장된 각 개별 시계열을 **item**이라고 부릅니다. 예를 들어 수요 예측에서는 서로 다른 제품, 금융 데이터에서는 서로 다른 주식이 각 item에 해당합니다. 이러한 구성을 시계열의 **panel**이라고도 합니다.

**주의**: 이는 다변량(multivariate) 예측과는 다릅니다. AutoGluon은 서로 다른 item 간의 상호 작용을 모델링하지 않고 각 시계열에 대해 독립적으로 예측을 생성합니다.

`TimeSeriesDataFrame`은 `pandas.DataFrame`을 상속하므로 pandas의 모든 메서드를 사용할 수 있습니다.

## 3.2 Training time series models

`TimeSeriesPredictor`는 여러 단계의 미래를 예측합니다. 예측 기간(forecast horizon)을 `prediction_length`로 지정합니다.

본 실습 데이터셋은 시간별 빈도이므로 `prediction_length=48`로 설정하여 48시간 후까지 예측합니다.

- `path`: 학습된 모델 저장 위치
- `target`: 예측 대상 열
- `eval_metric`: 모델 순위 결정 기준 ([MASE](https://en.wikipedia.org/wiki/Mean_absolute_scaled_error) 사용)
"""

predictor = TimeSeriesPredictor(
    prediction_length=48,
    path="autogluon-m4-hourly",
    target="target",
    eval_metric="MASE",
)

predictor.fit(
    train_data,
    presets="medium_quality",
    time_limit=180,  # 3분 (실습용)
)

"""### Time Series Preset

`medium_quality` preset은 다음 모델들을 학습합니다.

- Simple baselines: `Naive`, `SeasonalNaive`
- Statistical models: `ETS`, `Theta`
- Tree-based models: `RecursiveTabular`, `DirectTabular` (LightGBM 기반)
- Deep learning: `TemporalFusionTransformer`
- Weighted ensemble (위 모델들의 결합)

사용 가능한 다른 preset: `fast_training`, `high_quality`, `best_quality`. 품질이 높을수록 학습 시간이 길어집니다.

AutoGluon은 주어진 `time_limit` 내에서 가능한 한 많은 모델을 학습한 후, 내부 validation set에서 성능 순위를 매깁니다. 기본 validation set은 `train_data`의 각 시계열에서 마지막 `prediction_length`만큼을 떼어내어 구성됩니다.

## 3.3 Prediction & Visualization
"""

predictions = predictor.predict(train_data)
predictions.head()

"""AutoGluon은 평균(예상값) 예측 외에도 **확률적(probabilistic) 예측**을 생성합니다. 즉, 미래 값의 분포에 대한 사분위수(quantile)를 함께 제공하여 결과의 불확실성을 표현합니다.

예시: `0.1` 사분위수가 `500.0`이면 "목표 값이 500.0보다 낮을 확률이 10%"라는 의미입니다.

아래에서 4개의 시계열에 대해 평균 예측값과 함께 10%, 90% 사분위수를 plotting하여 잠재적 결과 범위를 시각화합니다.
"""

import matplotlib.pyplot as plt

test_data = TimeSeriesDataFrame.from_path("https://autogluon.s3.amazonaws.com/datasets/timeseries/m4_hourly_subset/test.csv")

predictor.plot(test_data, predictions, quantile_levels=[0.1, 0.9], max_history_length=200, max_num_item_ids=4)

"""## 3.4 Evaluating models

`leaderboard()` 메서드로 AutoGluon이 학습한 각 모델의 성능을 비교할 수 있습니다. Test data에는 forecast horizon (마지막 `prediction_length`개 값)과 과거 데이터가 모두 포함됩니다.

AutoGluon leaderboard에서는 점수가 높을수록 예측 성능이 우수합니다. 따라서 MASE 점수에 `-1`을 곱한 값("negative MASE")이 표시되며, 0에 가까울수록 더 정확한 예측을 의미합니다.
"""

predictor.leaderboard(test_data)

"""# Cheatsheet

## Tabular

![Tabular Cheatsheet](https://raw.githubusercontent.com/Innixma/autogluon-doc-utils/main/docs/cheatsheets/stable/autogluon-cheat-sheet.jpeg)

## Multimodal

![Multimodal Cheatsheet](https://automl-mm-bench.s3-accelerate.amazonaws.com/cheatsheet/stable/automm.jpeg)

## Time Series

![Time Series Cheatsheet](https://raw.githubusercontent.com/Innixma/autogluon-doc-utils/main/docs/cheatsheets/stable/timeseries/autogluon-cheat-sheet-ts.jpeg)

## 추가 학습

- [AutoGluon Documentation](https://auto.gluon.ai/stable/index.html)
- [TabularPredictor API](https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.html)
- [MultiModalPredictor API](https://auto.gluon.ai/stable/api/autogluon.multimodal.MultiModalPredictor.html)
- [TimeSeriesPredictor API](https://auto.gluon.ai/stable/api/autogluon.timeseries.TimeSeriesPredictor.html)
"""